server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${CA_PASSWORD}
    key-store-type: PKCS12
    key-alias: server
    enabled: true
spring:
  application:
    name: rbpo_babok
  datasource:
    url: jdbc:postgresql://localhost:5432/data
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  accessExpiration: 600000
  refreshExpiration: 3600000